version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      astro-ecosystem:
        patterns:
          - "astro"
          - "@astrojs/*"
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependabot"
      - "dependencies"
